// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-gefPEY0KtgQQlCfbgpxU-BP7vd3aWZ8',
    appId: '1:587240536640:web:52061306969bad2a80fda5',
    messagingSenderId: '587240536640',
    projectId: 'interview-hatk',
    authDomain: 'interview-hatk.firebaseapp.com',
    databaseURL: 'https://interview-hatk-default-rtdb.firebaseio.com',
    storageBucket: 'interview-hatk.firebasestorage.app',
    measurementId: 'G-LERQCY1WSB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-gefPEY0KtgQQlCfbgpxU-BP7vd3aWZ8',
    appId: '1:587240536640:web:adfbc9409c9000fb80fda5',
    messagingSenderId: '587240536640',
    projectId: 'interview-hatk',
    authDomain: 'interview-hatk.firebaseapp.com',
    databaseURL: 'https://interview-hatk-default-rtdb.firebaseio.com',
    storageBucket: 'interview-hatk.firebasestorage.app',
    measurementId: 'G-V02ZCJR6W1',
  );
}
